# Generated by Django 3.2.7 on 2021-09-30 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posion', models.CharField(max_length=250)),
                ('time', models.TimeField()),
                ('payment', models.FloatField()),
                ('company', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(default=12)),
                ('email', models.EmailField(default='example@gmail.com', max_length=254)),
                ('location', models.GenericIPAddressField()),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('icon', models.ImageField(upload_to='uploads/%Y/%m/%')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='izoh')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='comment/')),
                ('like', models.CharField(default=0, max_length=100)),
                ('dislike', models.CharField(default=0, max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.shipper')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(default=12)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=250)),
                ('pick_up', models.DateField()),
                ('delivery_date', models.DateField()),
                ('truckload_type', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(default=12)),
                ('email', models.EmailField(default='example@gmail.com', max_length=254)),
                ('from_city', models.CharField(default='state/city', max_length=250)),
                ('to_sity', models.CharField(default='state/city', max_length=250)),
                ('comments', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.comment')),
            ],
        ),
    ]
