# Generated by Django 3.2.7 on 2021-10-02 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactuser',
            name='comment',
        ),
        migrations.AddField(
            model_name='contactuser',
            name='comments',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactuser',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='career',
            name='location',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='career',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='comments',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='truckload_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.shipper'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
