# Generated by Django 3.2.7 on 2021-10-02 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211002_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='time',
            field=models.TimeField(default=datetime.timezone),
        ),
    ]
