# Generated by Django 3.2.7 on 2021-10-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_career_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='time',
            field=models.CharField(max_length=250),
        ),
    ]
